resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml

commonLabels:
  app.kubernetes.io/name: kuberay
  app.kubernetes.io/component: kuberay-operator
