apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kueue-prepopulator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-prepopulator-role
subjects:
- kind: ServiceAccount
  name: kueue-prepopulator
  namespace: kueue-system
