---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- if .Values.enableCertManager }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kueue.fullname" . }}-serving-cert
    {{- end }}
    controller-gen.kubebuilder.io/version: v0.12.0
  name: admissionchecks.kueue.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: {{ include "kueue.fullname" . }}-webhook-service
          namespace: '{{ .Release.Namespace }}'
          path: /convert
      conversionReviewVersions:
      - v1
  group: kueue.x-k8s.io
  names:
    kind: AdmissionCheck
    listKind: AdmissionCheckList
    plural: admissionchecks
    singular: admissioncheck
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: AdmissionCheck is the Schema for the admissionchecks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AdmissionCheckSpec defines the desired state of AdmissionCheck
            properties:
              controllerName:
                description: ControllerName identifies the controller managing this
                  condition.
                type: string
              parameters:
                description: Parameters identifies the resource providing additional
                  check parameters.
                properties:
                  apiGroup:
                    description: ApiGroup is the group for the resource being referenced.
                    type: string
                  kind:
                    description: Kind is the type of the resource being referenced.
                    type: string
                  name:
                    description: Name is the name of the resource being referenced.
                    type: string
                required:
                - apiGroup
                - kind
                - name
                type: object
              retryDelayMinutes:
                description: RetryDelayMinutes specifies the duration in minutes between
                  tow checks for the same workload.
                format: int64
                type: integer
            type: object
          status:
            description: AdmissionCheckStatus defines the observed state of AdmissionCheck
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
