version: 2
updates:

  # Maintain dependencies for go.
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/hack/internal/tools"
      - "/site"
      - "/cmd/kueueviz/backend"
      - "/cmd/experimental/kueue-populator"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
      - "dependencies"
      - "area/dependency"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
    ignore:
      # Ignore major and minor versions for dependencies updates
      # Allow patches and security updates.
      - dependency-name: k8s.io/*
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ok-to-test"
      - "release-note-none"
      - "dependencies"
      - "area/dependency"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
          - "minor"
          - "patch"

  # Maintain Dockerfiles
  - package-ecosystem: "docker"
    directories:
      - "/cmd/kueueviz/frontend"
      - "/hack/agnhost"
      - "/hack/cypress"
      - "/hack/depcheck"
      - "/hack/shellcheck"
      - "/hack/multikueue/secretreader"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
      - "dependencies"
      - "area/dependency"

  # Maintain npm dependencies
  - package-ecosystem: "npm"
    directories:
      - /cmd/kueueviz/frontend
      - /site
      - /test/e2e/kueueviz
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
      - "dependencies"
      - "area/dependency"
    groups:
      mui-packages:
        patterns:
          - "@mui/*"
      all:
        update-types:
          - "minor"
          - "patch"
