apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-clusterprofiles-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-clusterprofiles-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
