[build]
  base = "site"
  publish = "public"
  command = "npm install && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.145.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://kueue.sigs.k8s.io/"

[context.deploy-preview]
  command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"
