apiVersion: v2
name: kueue-populator
description: A Helm chart for Kueue Prepopulator setup including Kueue, LocalQueue Creator, and default resources.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: kueue
    version: "0.14.4"
    repository: "oci://registry.k8s.io/kueue/charts"
    condition: kueue.enabled
