apiVersion: v2
name: kueue-populator
description: A Helm chart for Kueue Populator setup including Kueue, LocalQueue Creator, and default resources.
type: application
version: 0.15.3
appVersion: "v0.15.3"
dependencies:
  - name: kueue
    version: "~0.15.3"
    repository: "file://../../../../../charts/kueue"
    condition: kueue.enabled
