apiVersion: v2
name: kueue-populator
description: A Helm chart for Kueue Populator setup including Kueue, LocalQueue Creator, and default resources.
type: application
version: 0.14.5
appVersion: "v0.14.5"
dependencies:
  - name: kueue
    version: "~0.14.5"
    repository: "file://../../../../../charts/kueue"
    condition: kueue.enabled
