apiVersion: v2
name: preemption-cost-controller
description: A Helm chart for deploying the experimental Kueue preemption-cost controller.
type: application
version: 0.15.2
appVersion: "v0.15.2"
dependencies:
  - name: kueue
    version: "~0.15.2"
    repository: "file://../../../../../charts/kueue"
    condition: kueue.enabled
