# permissions for end users to view workloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "kueue.fullname" . }}-workload-viewer-role'
  labels:
  {{- include "kueue.labels" . | nindent 4 }}
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.kueue.x-k8s.io/batch-user: "true"
rules:
  - apiGroups:
      - kueue.x-k8s.io
    resources:
      - workloads
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kueue.x-k8s.io
    resources:
      - workloads/status
    verbs:
      - get
