# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/kueue.x-k8s.io_localqueues.yaml
- bases/kueue.x-k8s.io_clusterqueues.yaml
- bases/kueue.x-k8s.io_cohorts.yaml
- bases/kueue.x-k8s.io_workloads.yaml
- bases/kueue.x-k8s.io_resourceflavors.yaml
- bases/kueue.x-k8s.io_admissionchecks.yaml
- bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
- bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
- bases/kueue.x-k8s.io_multikueueconfigs.yaml
- bases/kueue.x-k8s.io_multikueueclusters.yaml
- bases/kueue.x-k8s.io_topologies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_localqueues.yaml
#- path: patches/webhook_in_clusterqueues.yaml
#- path: patches/webhook_in_workloads.yaml
#- path: patches/webhook_in_resourceflavors.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_clusterqueues.yaml
- path: patches/cainjection_in_workloads.yaml
- path: patches/cainjection_in_resourceflavors.yaml
- path: patches/cainjection_in_cohorts.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
