# permissions for end users to edit queuedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuedworkload-editor-role
  labels:
    rbac.kueue.x-k8s.io/batch-admin: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queuedworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queuedworkloads/status
  verbs:
  - get
