apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.visibility.kueue.x-k8s.io
spec:
  group: visibility.kueue.x-k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: '{{ include "kueue.fullname" . }}-visibility-server'
    namespace: '{{ .Release.Namespace }}'
  version: v1alpha1
  versionPriority: 100
