apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  labels:
  {{- include "kueue.labels" . | nindent 4 }}
  name: '{{ include "kueue.fullname" . }}-visibility'
  namespace: '{{ .Release.Namespace }}'
spec:
  limited:
    lendablePercent: 90
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
    nominalConcurrencyShares: 10
  type: Limited
