apiVersion: v1
kind: ConfigMap
metadata:
  name: preemption-cost-controller-config
  namespace: kueue-system
data:
  controller_manager_config.yaml: |
    enableRunningPhaseIncrement: false
    runningPhaseIncrement: 1
    maxCost: 100000
