apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- manager/manager.yaml
- manager/controller_config_map.yaml

images:
- name: us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue-populator
  newName: us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue-populator
  newTag: e533ba333-dirty
namespace: kueue-system
