apiVersion: v1
kind: ConfigMap
metadata:
  name: kueue-localqueue-controller-config
  namespace: kueue-system
data:
  controller_manager_config.yaml: |
    localQueueName: default
    # managedJobsNamespaceSelector:
    #   matchLabels:
    #     key: value
