apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- manager/manager.yaml

images:
- name: localqueue-creator
  newName: us-central1-docker.pkg.dev/k8s-staging-images/kueue/localqueue-creator
  newTag: ad38142d8-dirty
namespace: kueue-system
