apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- localqueue-creator.yaml

images:
- name: localqueue-creator
  newName: us-central1-docker.pkg.dev/k8s-staging-images/kueue/localqueue-creator
  newTag: b550912ee-dirty
namespace: kueue-system
