# RHOAI configuration for Kueue.

# Adds namespace to all resources.
namespace: opendatahub

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: kueue-

configMapGenerator:
- name: rhoai-config
  envs:
    - params.env

configurations:
  - params.yaml

vars:
- name: image
  objref:
    kind: ConfigMap
    name: rhoai-config
    apiVersion: v1
  fieldref:
    fieldpath: data.odh-kueue-controller-image

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: kueue
  app.kubernetes.io/component: controller

resources:
- ../components/crd
- ../components/rbac
- ../components/manager
- ../components/internalcert
- ../components/webhook
- monitor.yaml
- binding_admin_roles.yaml
- webhook_network_policy.yaml
- batch-user-rolebinding.yaml
- kueue-metrics-service.yaml

patches:
# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
- path: manager_config_patch.yaml
- path: manager_webhook_patch.yaml
- path: manager_metrics_patch.yaml
- path: auth_proxy_service_patch.yaml
- path: mutating_webhook_patch.yaml
- path: validating_webhook_patch.yaml
- path: clusterqueue_viewer_role_patch.yaml
- path: remove_default_namespace.yaml
